env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb
  - plugin:react/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: ['./tsconfig.json', './tsconfig.node.json']
plugins:
  - react
rules:
  {
    'react/jsx-filename-extension': [1, { 'extensions': ['.tsx'] }],
    'react/react-in-jsx-scope': 'off',
    'react/jsx-props-no-spreading': ['off', { 'html': 'ignore' }],
    'import/extensions': ['error', 'ignorePackages', { 'js': 'never', 'jsx': 'never', 'ts': 'never', 'tsx': 'never' }],
    'import/prefer-default-export': 'off',
    'no-underscore-dangle': 'off',
    'no-shadow': 'off',
    '@typescript-eslint/no-shadow': ['error'],
    'react/require-default-props': 'off',
  }
settings:
  {
    'react': { 'version': 'detect' },
    'import/resolver': { node: { extensions: ['.ts', '.js', '.tsx', '.jsx'] }, typescript: true },
  }
